import React from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { FileJson, FileText, FileSpreadsheet, Copy, Share2 } from "lucide-react";
import { toast } from "@/components/ui/use-toast";

function downloadAsFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export default function ExportDialog({ variant, open, onClose }) {
  if (!variant) return null;

  const handleExport = (format) => {
    const title = variant.title || "content";
    const safeName = title.replace(/[^a-z0-9]/gi, "_").toLowerCase();
    const timestamp = new Date().toISOString().split('T')[0];
    const filename = `${safeName}_${timestamp}`;

    if (format === "json") {
      downloadAsFile(JSON.stringify(variant, null, 2), `${filename}.json`, "application/json");
    } else if (format === "csv") {
      const csv = `"Title","Content","Word Count"\n"${(variant.title || "").replace(/"/g, '""')}\n"${variant.content.replace(/"/g, '""')}\n"${variant.word_count || ""}";`;
      downloadAsFile(csv, `${filename}.csv`, "text/csv");
    } else if (format === "pdf") {
      // Create a simple HTML for PDF
      const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>${variant.title || 'Content'}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; line-height: 1.6; }
            h1 { color: #333; border-bottom: 2px solid #007bff; padding-bottom: 10px; }
            .meta { color: #666; font-size: 14px; margin-bottom: 20px; }
            .content { white-space: pre-wrap; }
          </style>
        </head>
        <body>
          <h1>${variant.title || 'Generated Content'}</h1>
          <div class="meta">
            <p>Word Count: ${variant.word_count || 'N/A'} words</p>
            <p>Generated on: ${new Date().toLocaleDateString()}</p>
          </div>
          <div class="content">${variant.content}</div>
        </body>
        </html>
      `;
      downloadAsFile(htmlContent, `${filename}.html`, "text/html");
      toast({ 
        title: "Exported as HTML", 
        description: "Open in browser and print to PDF", 
        duration: 3000 
      });
      onClose();
      return;
    } else if (format === "social") {
      // Social-ready format with hashtags and formatting
      const socialContent = `${variant.title ? `${variant.title}

` : ""}${variant.content}

---
Generated by Creative Studio OS`;
      downloadAsFile(socialContent, `${filename}_social.txt`, "text/plain");
    } else {
      downloadAsFile(variant.content, `${filename}.txt`, "text/plain");
    }
    toast({ title: `Exported as ${format.toUpperCase()}`, duration: 1500 });
    onClose();
  };

  const handleCopyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(variant.content);
      toast({ title: "Copied to clipboard!", duration: 1500 });
      onClose();
    } catch (err) {
      toast({ 
        title: "Failed to copy", 
        description: "Please try again", 
        variant: "destructive" 
      });
    }
  };

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-sm">
        <DialogHeader>
          <DialogTitle className="font-display">Export Variant</DialogTitle>
          <DialogDescription>Choose a format to export this content.</DialogDescription>
        </DialogHeader>
        <div className="flex flex-col gap-2 pt-2">
          <Button variant="outline" className="justify-start gap-3 h-11" onClick={() => handleExport("txt")}>
            <FileText className="w-4 h-4 text-primary" /> Plain Text (.txt)
          </Button>
          <Button variant="outline" className="justify-start gap-3 h-11" onClick={() => handleExport("pdf")}>
            <FileText className="w-4 h-4 text-blue-500" /> PDF (HTML format)
          </Button>
          <Button variant="outline" className="justify-start gap-3 h-11" onClick={() => handleExport("social")}>
            <Share2 className="w-4 h-4 text-green-500" /> Social-Ready Format
          </Button>
          <Button variant="outline" className="justify-start gap-3 h-11" onClick={() => handleExport("json")}>
            <FileJson className="w-4 h-4 text-primary" /> JSON
          </Button>
          <Button variant="outline" className="justify-start gap-3 h-11" onClick={() => handleExport("csv")}>
            <FileSpreadsheet className="w-4 h-4 text-primary" /> CSV
          </Button>
          <Button 
            className="justify-start gap-3 h-11 bg-primary hover:bg-primary/90" 
            onClick={handleCopyToClipboard}
          >
            <Copy className="w-4 h-4" /> Copy to Clipboard
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}